#!/usr/bin/env bash
################################################################### SETUP ########################################################################
set -o errexit -o errtrace -o nounset
##################################################################################################################################################

revision_range="$(git outgoing-commits-revision-range)"

if temp_commits="$(git log --pretty='format:%s %h' "${revision_range}" 2> /dev/null | grep -Ei '^(temp|tmp)')"; then
  # shellcheck disable=SC2016
  echo 'Trying to push a commit that starts with a `temp` or `tmp` message. Matching commits below, see `git log "'"${revision_range}"'"` for full listing.'
  echo "$temp_commits"
  exit 1
fi

exit 0
