#!/usr/bin/env bash
################################################################### SETUP ########################################################################
set -o errexit -o errtrace -o nounset
##################################################################################################################################################

current_branch="$(git current-branch)"
default_branch="$(git default-branch)"

if test "${current_branch}" = "${default_branch}" || test "${REMOTE_REF}" = "refs/heads/${default_branch}"; then
  echo "Trying to push to default branch [${default_branch}]"
  exit 1
fi

exit 0
